/* var urlUploadFile generated by php*/
$(function() {
	function initTextFilesUI() {
		$('#typeUpload').buttonset();
		$('#preview,#submit,#typePopup').button();
		$( "#filesProgress" ).progressbar({
			value: false
		 });
	}
	function initTextFilesBehaviour() {
		$('#typePopup').click(showUploadPopup);
		$('#preview').click(textFilesPreviw);
	}

	function textFilesPreviw() {
		var filesForm = $('#files')[0].files;
		var options = {size : packetSize,
			progressHandler : progressHandler,
					destination : urlUploadFile};

		for(var i = 0; i < filesForm.length; i++) {
			options.file = filesForm[i];
			new jsUpload(options);
		}
	}

	initTextFilesUI();
	initTextFilesBehaviour();
 });

function progressHandler() {

}

function showUploadPopup() {
	$('#files').click();
}