/* var URL_UPLOAD_FILE generated by php*/
/* var packetSize generated by php*/
var reconnectionTimeout = 5000;

function showUploadPopup() {
	$('#files').click();
}

/**
 * Returns a random number between min and max
 */
function getRandom (min, max) {
    return Math.random() * (max - min) + min;
}